_target_: theorem_contrastive_training.CLSPoolingEncoder
name: bert-base
model_name: bert-base-uncased
hidden_dim: 768
output_dim: 2048

lora_target_modules:
- query
- key
- value

lora:
  enabled: false
