_target_: theorem_contrastive_training.LastTokenEncoder
name: deepscaler-1.5b
model_name: agentica-org/DeepScaleR-1.5B-Preview
hidden_dim: 1536
output_dim: 2048

lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj

lora:
  enabled: true
