# Qwen 1.5B model configuration
name: qwen-2.5-math-7b
model_name: Qwen/Qwen2.5-Math-7B-Instruct
model_type: last_token_pooling
hidden_dim: 1536
lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]