name: qwen-14b
model_name: Qwen/Qwen3-14B
hidden_dim: 5120
model_type: last_token_pooling
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
output_dim: 2048
use_gradient_checkpointing: false
quantization_config: null
