_target_: theorem_contrastive_training.LastTokenEncoder
name: qwen-2.5-math-7b
model_name: Qwen/Qwen2.5-Math-7B-Instruct
hidden_dim: 3584
output_dim: 2048

lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj

lora:
  enabled: true
