_target_: theorem_contrastive_training.LastTokenEncoder
name: qwen-1.5b
model_name: deepseek-ai/deepseek-r1-distill-qwen-1.5b
hidden_dim: 1536
output_dim: 2048

lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj

lora:
  enabled: true
