# Fast training configuration for testing
global_batch_size: 128
micro_batch_size: 6
stream_chunk_size: 128
tau: 0.07
lr: 1e-3
num_epochs: 2
max_length: 256
output_dim: 512
drop_last: true

# LoRA configuration
lora:
  enabled: true
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05