global_batch_size: [64, 64, 1024]  # Gradual increase, for optimal flop/loss trade off
micro_batch_size: 8
stream_chunk_size: 256
tau: 0.07
lr: 2e-4
num_epochs: 20
max_length: 256
output_dim: 2048
drop_last: true
use_amp: true  # Enable automatic mixed precision for memory efficiency

# LoRA configuration
lora:
  enabled: true
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
