# Fast training configuration for testing
global_batch_size: 1028
micro_batch_size: 32
stream_chunk_size: 256
tau: 0.07
lr: 1.5e-4
num_epochs: 10
max_length: 256
output_dim: 512
drop_last: true

# LoRA configuration
lora:
  enabled: false
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05