# configs/default_experiment.yaml

data:
  jsonl_path: "./data/wiki_articles.jsonl"
  train_sample_size: 1000
  val_sample_size: 100
  max_length: 512
  batch_size: 32
  num_workers: 4
  cite_samples_per_article: 1
  val_cite_samples_per_article: 10

model:
  model_name: "bert-base-uncased"
  max_length: 512
  cite_token: "<CITE>"
  ref_token: "<REF>"
  temperature: 0.07
  checkpoint_dir: "checkpoints"

training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.00015
  temperature: 0.1
  num_workers: 4
  gradient_clip_value: 1.0
  scheduler_patience: 2
  scheduler_factor: 0.5
  eval_k_values: [1, 3, 5, 10, 50]
  save_every_n_epochs: 1
  early_stopping_patience: 3
  checkpoint_dir: "checkpoints"
  experiment_name: "citation_matching_baseline"