experiment_name: default_experiment
output_dir: experiments

model:
  model_name: bert-base-uncased
  max_length: 512
  cite_token: <CITE>
  ref_token: <REF>
  temperature: 0.07

training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.00015
  temperature: 0.1
  num_workers: 4
  gradient_clip_value: 1.0
  scheduler_patience: 2
  scheduler_factor: 0.5
  eval_k_values: [1, 3, 5, 10, 50, 100, 1000]

data:
  data_path: ./data/wiki_articles.jsonl
  train_sample_size: 10000
  val_sample_size: 50000
  val_samples_per_article: 3
  train_samples_per_article: 1